<a href="https://colab.research.google.com/github/Mendoza-JM/58013-LinearAlgebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Problem 1
import numpy as np
A = np.array ([[1,2,3],[4,5,6]])
B = np.array ([[1,2],[3,4],[5,6]])
C = np.array ([[1,2,3],[4,5,6],[7,8,9]])
D = np.array ([[1,2],[3,4]])

print("a) AB = ")
print(np.dot(A,B))

print("\nb) D + D = ")
print(np.add(D,D))

print("\nc) 2C = ")
print(2*C)

a) AB = 
[[22 28]
 [49 64]]

b) D + D = 
[[2 4]
 [6 8]]

c) 2C = 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [11]:
#Problem 2
A = np.array ([2,7,4])
B = np.array ([3,9,8])

print("Cross product of A & B = ")
print(np.cross(A,B))

Cross product of A & B = 
[20 -4 -3]
