<a href="https://colab.research.google.com/github/Mendoza-JM/58013-LinearAlgebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [ ]:
A = np.array([[30,10,120],[40,20,200],[50,40,360]])
B = np.array([12500,18000,25700])
print(A)
print(B)

solve = np.linalg.solve(A,B)
print(solve)

[[ 30  10 120]
 [ 40  20 200]
 [ 50  40 360]]
[12500 18000 25700]
[330. 140.  10.]


In [3]:
from sympy import symbols, Eq, solve

# Define symbolic variables
x1, x2, x3 = symbols('x1 x2 x3')

# Define the equations
eq1 = Eq(30*x1 + 10*x2 + 120*x3, 12500)
eq2 = Eq(40*x1 + 20*x2 + 200*x3, 18000)
eq3 = Eq(50*x1 + 40*x2 + 360*x3, 25700)

# Solve the system of equations
sol = solve((eq1, eq2, eq3), (x1, x2, x3))

# Extract the solutions
x1 = sol[x1]
x2 = sol[x2]
x3 = sol[x3]

print(f"Price per sack of flour: = {x1} Pesos")
print(f"Price per pack of yeast: = {x2} Pesos")
print(f"Price per egg = {x3} Pesos")


Price per sack of flour: = 330 Pesos
Price per pack of yeast: = 140 Pesos
Price per egg = 10 Pesos
