<a href="https://colab.research.google.com/github/Mendoza-JM/58013-LinearAlgebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [5]:
A = np.array([[30,10,120],[40,20,200],[50,40,360]])
B = np.array([12500,18000,25700])
print(A)
print(B)

solve = np.linalg.solve(A,B)
print(solve)

[[ 30  10 120]
 [ 40  20 200]
 [ 50  40 360]]
[12500 18000 25700]
[330. 140.  10.]


In [6]:
from sympy import symbols, Eq, solve

# Define symbolic variables
x1, x2, x3 = symbols('x1 x2 x3')

# Define the equations
eq1 = Eq(3*x1 - 9*x3, 33)
eq2 = Eq(7*x1 - 4*x2 - x3, -15)
eq3 = Eq(4*x1 + 6*x2 + 5*x3, -6)

# Solve the system of equations
sol = solve((eq1, eq2, eq3), (x1, x2, x3))

# Extract the solutions
x1 = sol[x1]
x2 = sol[x2]
x3 = sol[x3]

print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")


x1 = -1
x2 = 3
x3 = -4


In [4]:
# Given data for each month
month1 = {
    'flour_sacks': 30,
    'yeast_packs': 10,
    'eggs': 120,
    'total_cost': 12500
}

month2 = {
    'flour_sacks': 40,
    'yeast_packs': 20,
    'eggs': 200,
    'total_cost': 18000
}

month3 = {
    'flour_sacks': 50,
    'yeast_packs': 40,
    'eggs': 360,
    'total_cost': 25700
}

# Calculate the prices per unit for each item
price_per_sack = month1['total_cost'] / (month1['flour_sacks'] + month2['flour_sacks'] + month3['flour_sacks'])
price_per_pack_of_yeast = month1['total_cost'] / (month1['yeast_packs'] + month2['yeast_packs'] + month3['yeast_packs'])
price_per_egg = month1['total_cost'] / (month1['eggs'] + month2['eggs'] + month3['eggs'])

# Display the results
print(f"Price per sack of flour: {price_per_sack:.2f} pesos")
print(f"Price per pack of yeast: {price_per_pack_of_yeast:.2f} pesos")
print(f"Price per egg: {price_per_egg:.2f} pesos")


Price per sack of flour: 104.17 pesos
Price per pack of yeast: 178.57 pesos
Price per egg: 18.38 pesos
