<a href="https://colab.research.google.com/github/Mendoza-JM/58013-LinearAlgebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [ ]:
## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)


-235.0000000000002

In [ ]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
C = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(A)
print(B)
print(C,"\n")

# Property 1: Associativite property
print("Property 1: Associativite property")
result1 = np.dot(np.dot(A, B), C)
result2 = np.dot(A, np.dot(B, C))
print(result1)
print(result2,"\n")

# Property 2: Distributive property
print("Property 2: Distributive property")
result3 = np.dot(A, B + C)
result4 = np.dot(A, B) + np.dot(A, C)
print(result3)
print(result4,"\n")

# Property 3: Multiplicative identity property
print("Property 3: Multiplicative identity property")
identity_matrix = np.identity(3)
result5 = np.dot(A, identity_matrix)
result6 = np.dot(identity_matrix, A)
print(result5)
print(result6,"\n")

# Property 4: Dimension Property
print("Property 4: Dimension Property")
k = 2
result7 = np.dot(k * A, B)
result8 = k * np.dot(A, B)
print(result7)
print(result8,"\n")

# Property 5: Commutative property
print("Property 5: Commutative property")
result9 = np.dot(A, B)
result10 = np.dot(B, A)
print(result9)
print(result10,"\n")

# Property 6: Zero Matrix
print("Property 6: Zero Matrix")
zero_matrix = np.zeros((3, 3))
result11 = np.dot(A, zero_matrix)
result12 = np.dot(zero_matrix, A)
print(result11)
print(result12,"\n")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]] 

Property 1: Associativite property
[[ 324  396  468]
 [ 945 1152 1359]
 [1566 1908 2250]]
[[ 324  396  468]
 [ 945 1152 1359]
 [1566 1908 2250]] 

Property 2: Distributive property
[[ 66  66  66]
 [165 165 165]
 [264 264 264]]
[[ 66  66  66]
 [165 165 165]
 [264 264 264]] 

Property 3: Multiplicative identity property
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

Property 4: Dimension Property
[[ 60  48  36]
 [168 138 108]
 [276 228 180]]
[[ 60  48  36]
 [168 138 108]
 [276 228 180]] 

Property 5: Commutative property
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]] 

Property 6: Zero Matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

