<a href="https://colab.research.google.com/github/Mendoza-JM/58013-LinearAlgebra/blob/main/Vector_Spaces_and_Operatios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Raw Vector
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print("Vector A is ", A)
print("Vector B is ", B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


In [13]:
#size Dimension, Size
import numpy as np
ball1 = np.array([[1],[2],[3]])
print(ball1)

[[1]
 [2]
 [3]]


In [16]:
#Checking shapes
###Shapes tells us how many rows and columns are there
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)

b1 = np.shape(ball1)
b2 = np.shape(ball2)
ball = b1 + b2
print(ball)

x = np.ndim(ball1)
y = np.ndim(ball2)
print(x)
print(y)

[1 2 3]
[ 0  1 -1]
(3, 3)
1
1


In [20]:
#Spaces - Addition
A = np.array([4,3])
B = np.array([2,-5])
print(A+B)
R = np.add(A,B)
print(R)

[ 6 -2]
[ 6 -2]
[2 8]
[2 8]


In [21]:
#Spaces - Subtraction
print(A-B)
R1 = np.subtract(A,B)
print(R1)

[2 8]
[2 8]


In [23]:
#Scalar Product
S = np.array([2])
V = S*A
print(V)

[8 6]


In [29]:
#Multiply
C = np.array([4,3])
D = np.array([[2],[-5]])
print(C)
print(D)

output = np.multiply(C,D)
print(output)

[4 3]
[[ 2]
 [-5]]
[[  8   6]
 [-20 -15]]


In [38]:
#Property of Matrix
#Identity Matrix
X = np.eye(3,3)
print(X)

#Zero matrix
Y = np.zeros([5,5])
print(Y)

Z = np.full((3,3),7)
print(Z)

#Transpose of Matrix
print(np.transpose(output))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[  8 -20]
 [  6 -15]]
